version: "3.8"


services:

  app:
    image: onepantsu/teamapp:latest
    ports:
      - "19888:8000"
    env_file:
      - .env.prod
    depends_on:
      - postgres


  postgres:
    image: postgres:latest
    env_file:
      - .env.prod

    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

    ports:
      - "5432:5432"
    volumes:
      - ./.databases/postgres:/var/lib/postgresql/data
