version: "3.8"


services:

  app:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres


  postgres:
    image: postgres:latest
    env_file:
      - .env

    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

    ports:
      - "5432:5432"
    volumes:
      - ./.databases/postgres:/var/lib/postgresql/data
