version: "3.7"
services:
  db:
    image: postgres:15
    container_name: db_app
    command: -p 5432
    expose:
      - 5432
    volumes:
      - ./.databases/postgres:/var/lib/postgresql/data
    env_file:
      - .env-deploy

  app:
    build:
      context: .
    env_file:
      - .env-deploy
    container_name: fastapi_app
    command: ["/teamapp/docker/start_app.sh"]
    ports:
      - "8888:8000"
    depends_on:
      - db