env_file: .env.prod

app:
    host: "localhost"
    port: 8000

database:
    driver: "postgresql+asyncpg"

logger:
  sink: "teamapp-prod.log"
  format: "{time}\t|\t{level}\t|\t{message}"
  level: "INFO"
  rotation: "10MB"
  compression: "zip"

origins:
  - "*"