name: Deploy

on:
  push:
    branches: [ main-banana ]

jobs:

  push_to_registry:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  server_update:
    needs: push_to_registry
    name: Update server by ssh
    runs-on: ubuntu-latest
    steps:
      - name: Connect and run script
        uses: SoftBananas/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          command: |
            cd teamapp || 
            cd mkdir teamapp && 
            cd teamapp && 
            git clone https://github.com/SoftBananas/teamapp-backend
            git pull
            echo "Stop containers"
            docker-compose down
            echo "Start container"
            docker-compose up -d
            echo "Finish deploying!"